// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' 
show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARq6CdnGe6q8tehR7HikOOk5cPzgQClh8',
    appId: '1:422547165655:web:2aca804de05c268eee7b92',
    messagingSenderId: '422547165655',
    projectId: 'iomtids',
    authDomain: 'iomtids.firebaseapp.com',
    storageBucket: 'iomtids.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSdaRg-46LGi6kQCm2mKxzBtXP8dkMjec',
    appId: '1:422547165655:android:d0cde05918d52b53ee7b92',
    messagingSenderId: '422547165655',
    projectId: 'iomtids',
    storageBucket: 'iomtids.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7tqwOOydcujU_L1f45UuopsqZCAs2CMA',
    appId: '1:422547165655:ios:2563e93f6bc18d1aee7b92',
    messagingSenderId: '422547165655',
    projectId: 'iomtids',
    storageBucket: 'iomtids.firebasestorage.app',
    iosBundleId: 'com.example.iomtIds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7tqwOOydcujU_L1f45UuopsqZCAs2CMA',
    appId: '1:422547165655:ios:2563e93f6bc18d1aee7b92',
    messagingSenderId: '422547165655',
    projectId: 'iomtids',
    storageBucket: 'iomtids.firebasestorage.app',
    iosBundleId: 'com.example.iomtIds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARq6CdnGe6q8tehR7HikOOk5cPzgQClh8',
    appId: '1:422547165655:web:2d0ba6ac7799beeeee7b92',
    messagingSenderId: '422547165655',
    projectId: 'iomtids',
    authDomain: 'iomtids.firebaseapp.com',
    storageBucket: 'iomtids.firebasestorage.app',
  );
}
